### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by m1k1o** [matusnovak/homelab#6]
Name for ZFS metrics in grafana dashboard json contains `pool0`. That should be in environmet file or set by user otherwise.

**Comment by matusnovak** [comment]
Fixed via commit 2d1a0924f43a79ff500fabbdcb431f9c5adcf0fd also needs Docker image [matusnovak/prometheus-zfs](https://hub.docker.com/r/matusnovak/prometheus-zfs/tags) updated to version `v1.0.2` or later.
